version: "3.8"

services:

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: mon_projet_php
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            - mon_reseau

    nginx:
        image: nginx:alpine
        container_name: mon_projet_nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - database
        networks:
            - mon_reseau

    database:
        image: mysql:8.0
        container_name: mon_projet_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: onvasortir
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        volumes:
            - database_data:/var/lib/mysql
        ports:
            - "3307:3306"
        networks:
            - mon_reseau

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: mon_projet_phpmyadmin
        environment:
            PMA_HOST: database
            PMA_PORT: 3306
        ports:
            - "8081:80"
        depends_on:
            - database
        networks:
            - mon_reseau

volumes:
    database_data:

networks:
    mon_reseau:
        driver: bridge
